### ISSUE TITLE
"Failed to scrape metrics" in v1.1, worked  in v1.0.1

### ISSUE THREAD

**Issue by bdschaap** [splunk/splunk-connect-for-kubernetes#157]
**What happened**:
I am not receiving K8s metrics in Splunk.  I configured Splunk Connect for Kubernetes v1.1 in a one node cluster within Docker Desktop for Windows.  I am receiving the following error messages -
"[error]: #0 Failed to scrape metrics, error=, #<NoMethodError: undefined method `[]' for nil:NilClass>"
"[error]: #0 suppressed same stacktrace"
These errors appear in the kube:container:splunk-fluentd-k8s-metrics-agg sourcetype.

**What you expected to happen**:
I'm expecting K8s metrics to be sent to Splunk.  It works in v1.0.1 but no longer works in v1.1.

**How to reproduce it (as minimally and precisely as possible)**:
1) Configure Docker Desktop for Windows and enable Kubernetes
2) Install Splunk Connect for Kubernetes v1.1
3) Go to Splunk and you'll see that metrics are not available and the error messages above will be in the logs.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Ruby version (use `ruby --version`):
Not sure

- OS (e.g: `cat /etc/os-release`):
Windows Server 2019
- Splunk version:
7.2.6
- Others:
Splunk Connect for Kubernetes 1.1

**Comment by matthewmodestino** [comment]
Hi @bdschaap!

Can you share your values.yaml and grab the rendered runtime config from `kubectl logs -f` ? We dump the config when the pods spin up, handy for troubleshooting. 

Here is what I run in my docker for mac deploy:

```
#local config for metrics chart
splunk-kubernetes-metrics:
  kubernetes:
    clusterName: docker-for-mac
    kubeletPort: 10250
    useRestClientSSL: true
    insecureSSL: true
  buffer:
    chunk_limit_records: 10000
  aggregatorBuffer:
    chunk_limit_records: 10000
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-metrics
  splunk:
    hec:
      indexName: cm_metrics
```


Note the buffer configs to workaround this bug:
https://github.com/splunk/splunk-connect-for-kubernetes/issues/107

**Comment by jsiegele** [comment]
We run into the same Problem! 
Is there any workaround available?

Splunk Connect for Kubernetes 1.2

**Comment by matthewmodestino** [comment]
can you share details about your environment? I believe this happens when the node name is wrong or empty. Please see this PR:

https://github.com/splunk/splunk-connect-for-kubernetes/pull/197/files

**Comment by jsiegele** [comment]
I applied the fix of the appove commit, but the error persists:

```
    hec_token "xxxxx"
    host "8exxx5cb7be9"
...

2019-08-21 11:37:53 +0000 [info]: #0 Use URL https://172.200.2.8:10250/stats/ for creating client to query kubelet stats api
2019-08-21 11:37:53 +0000 [info]: #0 Use URL https://172.200.2.8:10250/metrics/cadvisor for creating client to query cadvisor metrics api
2019-08-21 11:37:53 +0000 [warn]: parameter 'cluster_name' in <source>
  @type kubernetes_metrics
  tag "kube.*"
  node_name "8exxx5cb7be9"
  use_rest_client_ssl true
  insecure_ssl true
  cluster_name k8s_banking-k8s-i
  interval 15s
</source> is not used.
2019-08-21 11:37:53 +0000 [info]: #0 starting fluentd worker pid=17 ppid=7 worker=0
2019-08-21 11:37:53 +0000 [info]: #0 fluentd worker is now running worker=0
2019-08-21 11:38:08 +0000 [error]: #0 Failed to scrape metrics, error=#<NoMethodError: undefined method `[]' for nil:NilClass>
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.1/lib/fluent/plugin/in_kubernetes_metrics.rb:308:in `emit_cpu_metrics'
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.1/lib/fluent/plugin/in_kubernetes_metrics.rb:362:in `emit_system_container_metrics'
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.1/lib/fluent/plugin/in_kubernetes_metrics.rb:534:in `block in emit_node_metrics'
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.1/lib/fluent/plugin/in_kubernetes_metrics.rb:533:in `each'
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.1/lib/fluent/plugin/in_kubernetes_metrics.rb:533:in `emit_node_metrics'
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.1/lib/fluent/plugin/in_kubernetes_metrics.rb:568:in `emit_metrics'
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.1/lib/fluent/plugin/in_kubernetes_metrics.rb:651:in `handle_response'
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.1/lib/fluent/plugin/in_kubernetes_metrics.rb:612:in `scrape_metrics'
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.5.4/lib/cool.io/loop.rb:88:in `run_once'
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.5.4/lib/cool.io/loop.rb:88:in `run'
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-08-21 11:38:23 +0000 [error]: #0 Failed to scrape metrics, error=#<NoMethodError: undefined method `[]' for nil:NilClass>
```

**Comment by matthewmodestino** [comment]
please share your configmap and deployment configs

**Comment by jsiegele** [comment]
Heapster: i guess this is an Artifact - the age of the heapster is not the same then the rest. I guess there is something we have to purge.

```
chown: /fluentd/etc/..data: Read-only file system
chown: /fluentd/etc/splunk/..data: Read-only file system
chown: /fluentd/etc/splunk/splunk_hec_token: Read-only file system
chown: /fluentd/etc/splunk/..2019_08_21_11_37_38.169915602/splunk_hec_token: Read-only file system
chown: /fluentd/etc/splunk/..2019_08_21_11_37_38.169915602: Read-only file system
chown: /fluentd/etc/splunk/..2019_08_21_11_37_38.169915602: Read-only file system
chown: /fluentd/etc/splunk: Read-only file system
chown: /fluentd/etc/splunk: Read-only file system
chown: /fluentd/etc/..2019_08_21_11_37_38.518177440/fluent.conf: Read-only file system
chown: /fluentd/etc/..2019_08_21_11_37_38.518177440: Read-only file system
chown: /fluentd/etc/..2019_08_21_11_37_38.518177440: Read-only file system
chown: /fluentd/etc/fluent.conf: Read-only file system
chown: /fluentd/etc: Read-only file system
chown: /fluentd/etc: Read-only file system
2019-08-21 11:37:43 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2019-08-21 11:37:46 +0000 [info]: Use URL https://172.200.2.8:10250/stats/summary for creating client to query kubelet summary api
2019-08-21 11:37:46 +0000 [info]: Use URL https://172.200.2.8:10250/stats/ for creating client to query kubelet stats api
2019-08-21 11:37:46 +0000 [info]: Use URL https://172.200.2.8:10250/metrics/cadvisor for creating client to query cadvisor metrics api
2019-08-21 11:37:46 +0000 [info]: using configuration file: <ROOT>
  <system>
    log_level info
  </system>
  <source>
    @type kubernetes_metrics
    tag "kube.*"
    node_name "8eaca5cd-1ec4-4ff9-9199-394f45cb7be9"
    use_rest_client_ssl true
    insecure_ssl true
    cluster_name k8s_banking-k8s-i
    interval 15s
  </source>
  <filter kube.**>
    @type record_modifier
    <record>
      metric_name ${tag}
      cluster_name k8s_banking-k8s-i
    </record>
  </filter>
  <filter kube.node.**>
    @type record_modifier
    <record>
      source ${record['node']}
    </record>
  </filter>
  <filter kube.pod.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}
    </record>
  </filter>
  <filter kube.sys-container.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}/${record['name']}
    </record>
  </filter>
  <filter kube.container.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}/${record['container-name']}
    </record>
  </filter>
  <match kube.**>
    @type splunk_hec
    data_type metric
    metric_name_key "metric_name"
    metric_value_key "value"
    protocol https
    hec_host "t-splunk.e-bk.m086"
    hec_port 443
    hec_token "fb900989-6864-4edb-8baf-935ec64e8a66"
    host "8eaca5cd-1ec4-4ff9-9199-394f45cb7be9"
    index "k8s_banking-k8s-i_metrics"
    source "${tag}"
    insecure_ssl true
    <buffer>
      @type "memory"
      chunk_limit_records 10000
      chunk_limit_size 100m
      flush_interval 5s
      flush_thread_count 1
      overflow_action block
      retry_max_times 3
      total_limit_size 400m
    </buffer>
  </match>
</ROOT>
2019-08-21 11:37:46 +0000 [info]: starting fluentd-1.4.0 pid=7 ruby="2.5.5"
2019-08-21 11:37:46 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins", "--under-supervisor"]
2019-08-21 11:37:50 +0000 [info]: gem 'fluent-plugin-kubernetes-metrics' version '1.1.1'
2019-08-21 11:37:50 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.0.1'
2019-08-21 11:37:50 +0000 [info]: gem 'fluent-plugin-splunk-hec' version '1.1.0'
2019-08-21 11:37:50 +0000 [info]: gem 'fluentd' version '1.4.0'
2019-08-21 11:37:50 +0000 [info]: adding filter pattern="kube.**" type="record_modifier"
2019-08-21 11:37:50 +0000 [info]: adding filter pattern="kube.node.**" type="record_modifier"
2019-08-21 11:37:50 +0000 [info]: adding filter pattern="kube.pod.**" type="record_modifier"
2019-08-21 11:37:50 +0000 [info]: adding filter pattern="kube.sys-container.**" type="record_modifier"
2019-08-21 11:37:50 +0000 [info]: adding filter pattern="kube.container.**" type="record_modifier"
2019-08-21 11:37:50 +0000 [info]: adding match pattern="kube.**" type="splunk_hec"
2019-08-21 11:37:51 +0000 [info]: adding source type="kubernetes_metrics"
2019-08-21 11:37:53 +0000 [info]: #0 Use URL https://172.200.2.8:10250/stats/summary for creating client to query kubelet summary api
2019-08-21 11:37:53 +0000 [info]: #0 Use URL https://172.200.2.8:10250/stats/ for creating client to query kubelet stats api
2019-08-21 11:37:53 +0000 [info]: #0 Use URL https://172.200.2.8:10250/metrics/cadvisor for creating client to query cadvisor metrics api
2019-08-21 11:37:53 +0000 [warn]: parameter 'cluster_name' in <source>
  @type kubernetes_metrics
  tag "kube.*"
  node_name "8eaca5cd-1ec4-4ff9-9199-394f45cb7be9"
  use_rest_client_ssl true
  insecure_ssl true
  cluster_name k8s_banking-k8s-i
  interval 15s
</source> is not used.
2019-08-21 11:37:53 +0000 [info]: #0 starting fluentd worker pid=17 ppid=7 worker=0
2019-08-21 11:37:53 +0000 [info]: #0 fluentd worker is now running worker=0
2019-08-21 11:38:08 +0000 [error]: #0 Failed to scrape metrics, error=#<NoMethodError: undefined method `[]' for nil:NilClass>
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.1/lib/fluent/plugin/in_kubernetes_metrics.rb:308:in `emit_cpu_metrics'
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.1/lib/fluent/plugin/in_kubernetes_metrics.rb:362:in `emit_system_container_metrics'
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.1/lib/fluent/plugin/in_kubernetes_metrics.rb:534:in `block in emit_node_metrics'
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.1/lib/fluent/plugin/in_kubernetes_metrics.rb:533:in `each'
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.1/lib/fluent/plugin/in_kubernetes_metrics.rb:533:in `emit_node_metrics'
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.1/lib/fluent/plugin/in_kubernetes_metrics.rb:568:in `emit_metrics'
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.1/lib/fluent/plugin/in_kubernetes_metrics.rb:651:in `handle_response'
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.1/lib/fluent/plugin/in_kubernetes_metrics.rb:612:in `scrape_metrics'
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.5.4/lib/cool.io/loop.rb:88:in `run_once'
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.5.4/lib/cool.io/loop.rb:88:in `run'
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2019-08-21 11:38:08 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-08-21 11:38:23 +0000 [error]: #0 Failed to scrape metrics, error=#<NoMethodError: undefined method `[]' for nil:NilClass>
  2019-08-21 11:38:23 +0000 [error]: #0 suppressed same stacktrace
2019-08-21 11:38:38 +0000 [error]: #0 Failed to scrape metrics, error=#<NoMethodError: undefined method `[]' for nil:NilClass>
  2019-08-21 11:38:38 +0000 [error]: #0 suppressed same stacktrace
2019-08-21 11:38:53 +0000 [error]: #0 Failed to scrape metrics, error=#<NoMethodError: undefined method `[]' for nil:NilClass>
  2019-08-21 11:38:53 +0000 [error]: #0 suppressed same stacktrace
2019-08-21 11:39:08 +0000 [error]: #0 Failed to scrape metrics, error=#<NoMethodError: undefined method `[]' for nil:NilClass>
  2019-08-21 11:39:08 +0000 [error]: #0 suppressed same stacktrace
2019-08-21 11:39:23 +0000 [error]: #0 Failed to scrape metrics, error=#<NoMethodError: undefined method `[]' for nil:NilClass>
  2019-08-21 11:39:23 +0000 [error]: #0 suppressed same stacktrace
2019-08-21 11:39:38 +0000 [error]: #0 Failed to scrape metrics, error=#<NoMethodError: undefined method `[]' for nil:NilClass>
  2019-08-21 11:39:38 +0000 [error]: #0 suppressed same stacktrace
2019-08-21 11:39:53 +0000 [error]: #0 Failed to scrape metrics, error=#<NoMethodError: undefined method `[]' for nil:NilClass>
  2019-08-21 11:39:53 +0000 [error]: #0 suppressed same stacktrace
2019-08-21 11:40:08 +0000 [error]: #0 Failed to scrape metrics, error=#<NoMethodError: undefined method `[]' for nil:NilClass>
  2019-08-21 11:40:08 +0000 [error]: #0 suppressed same stacktrace
2019-08-21 11:40:23 +0000 [error]: #0 Failed to scrape metrics, error=#<NoMethodError: undefined method `[]' for nil:NilClass>
  2019-08-21 11:40:23 +0000 [error]: #0 suppressed same stacktrace
2019-08-21 11:40:38 +0000 [error]: #0 Failed to scrape metrics, error=#<NoMethodError: undefined method `[]' for nil:NilClass>
  2019-08-21 11:40:38 +0000 [error]: #0 suppressed same stacktrace
2019-08-21 11:40:53 +0000 [error]: #0 Failed to scrape metrics, error=#<NoMethodError: undefined method `[]' for nil:NilClass>
  2019-08-21 11:40:53 +0000 [error]: #0 suppressed same stacktrace
2019-08-21 11:41:08 +0000 [error]: #0 Failed to scrape metrics, error=#<NoMethodError: undefined method `[]' for nil:NilClass>
  2019-08-21 11:41:08 +0000 [error]: #0 suppressed same stacktrace
```

**Comment by matthewmodestino** [comment]
is this resolvable from your cluster? `node_name "8eaca5cd-1ec4-4ff9-9199-394f45cb7be9"`

**Comment by jsiegele** [comment]
It seams that this name is not resolveable from the pod.

```
$ kubectl --namespace splunk-connect-k8s exec -it splunk-connect-release-splunk-kubernetes-metrics-kjtc6 -- sh
Unable to use a TTY - input is not a terminal or the right kind of file
nslookup 8eaca5cd-1ec4-4ff9-9199-394f45cb7be9

nslookup: can't resolve '(null)': Name does not resolve
```

**Comment by matthewmodestino** [comment]
yeah i am not sure if nslookup works in the pod, do you have a debug pod you can drop in the namespace that has curl in it to confirm?

What kubernetes variant are you running. this is a know issue in some variants. I have some workarounds depending on your situation.

**Comment by jsiegele** [comment]
We are running Pivotal PKS.

I will take a look at this debug pod!

Thanks for your help!!

**Comment by chaitanyaphalak** [comment]
Hey @jsiegele, I see you are running Splunk connect for kubernetes 1.1, we dont use heapster for metrics from that release.
And for the no method error, if you use the latest develop branch of https://github.com/splunk/fluent-plugin-kubernetes-metrics to build a docker image and use it you should be good. Let me know if you need more info.

**Comment by chaitanyaphalak** [comment]
During the following step please install missing dependencies

git clone https://github.com/splunk/fluent-plugin-kubernetes-metrics.git 
git checkout develop
gem install bundler
bundle update --bundler
bundle install
rake build -t -v
cp pkg/new.gem docker/new.gem
for previous step remove previous gem from docker/ if present
docker build --build-arg VERSION=1.1.0 --no-cache -t splunk/fluent-plugin-kubernetes-metrics:ci ./docker
docker tag splunk/fluent-plugin-kubernetes-metrics:ci your-repo
docker push your repo

**Comment by jsiegele** [comment]
Thank you very much!
Those are my steps, i had to do:

```
git checkout develop
sudo gem install bundler
sudo apt-get install ruby-dev
sudo gem install cool.io -v '1.5.4' --source 'https://rubygems.org/'
bundle update --bundler
bundle install
rake build -t -v
cp pkg/fluent-plugin-kubernetes-metrics-1.1.1.gem docker/.
docker build --build-arg VERSION=1.1.0 --no-cache -t
splunk/fluent-plugin-kubernetes-metrics:ci ./docker
```



Am Mi., 21. Aug. 2019 um 19:13 Uhr schrieb Chaitanya Phalak <
notifications@github.com>:

**Comment by jsiegele** [comment]
Hi!
After building a docker image with the Developer-Branch, the problem has not occurred.
So we look forward do get the metrics information in Splunk.

**Comment by chaitanyaphalak** [comment]
Cool let us know how it goes, please close the issue if you are happy with the resolution

**Comment by jsiegele** [comment]
I did not open this issue, so i don´t know if the initial problem is solved.
